#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get -y update
apt-get -y install haproxy=2.4.\*
sed -i '/errorfile 504/a listen mysimplesite' /etc/haproxy/haproxy.cfg
sed -i '/listen mysimplesite/a         bind :80' /etc/haproxy/haproxy.cfg
sed -i '/bind :80/a         mode http' /etc/haproxy/haproxy.cfg
sed -i '/mode http/a         server 652-web-01 3.239.59.231:80 check' /etc/haproxy/haproxy.cfg
sed -i '/server 652-web-01 3.239.59.231:80 check/a         server 652-web-02 34.236.134.251:80 check' /etc/haproxy/haproxy.cfg
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
service haproxy start
